#!/bin/bash

############################################################################################################
# Set debugging information
############################################################################################################

set -ux


############################################################################################################
# Set global variables
############################################################################################################

MY_HOSTNAME=`relation-get hostname`
MY_PORT=`relation-get port`


############################################################################################################
# Modify the sentinel configuration to monitor a master and restart sentinel so changes take effect.
############################################################################################################

sed -i.bak -e "s/monitor mymaster.*/monitor mymaster ${MY_HOSTNAME} ${MY_PORT} 2/" /etc/sentinel.conf

supervisorctl restart sentinel || supervisorctl start sentinel
